# Generated by Django 4.0.6 on 2022-07-15 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options_room_partcipants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='partcipants',
            new_name='participants',
        ),
    ]
